// Command import converts the vendored upstream exercise repository into the
// internal/catalog/exercises tree the application embeds.
//
// It is run by hand, and its output is committed. Two fields it writes are
// guesses that a human must confirm: kind, because a phrase heuristic
// classifies only 43 of 56 subjects, and expected_file for the four subjects
// whose expected files are a glob.
//
// Usage: go run ./tools/import -src third_party/exam_rank_02 -dst internal/catalog/exercises
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"exam02/internal/catalog"
	"gopkg.in/yaml.v3"
)

func main() {
	src := flag.String("src", "third_party/exam_rank_02", "vendored upstream repository")
	dst := flag.String("dst", "internal/catalog/exercises", "output directory")
	flag.Parse()

	if err := run(*src, *dst); err != nil {
		log.Fatal(err)
	}
}

func run(src, dst string) error {
	var imported, needsReview int
	for level := 1; level <= 4; level++ {
		levelDir := filepath.Join(src, "Level_"+strconv.Itoa(level))
		entries, err := os.ReadDir(levelDir)
		if err != nil {
			return fmt.Errorf("reading %s: %w", levelDir, err)
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			review, err := importOne(filepath.Join(levelDir, entry.Name()), dst, level, entry.Name())
			if err != nil {
				return fmt.Errorf("%s: %w", entry.Name(), err)
			}
			imported++
			if review != "" {
				needsReview++
				fmt.Printf("REVIEW %-20s %s\n", entry.Name(), review)
			}
		}
	}
	fmt.Printf("\nimported %d exercises, %d need review\n", imported, needsReview)
	return nil
}

// importOne writes one exercise directory. It returns a non-empty string
// describing what a human still has to check, or "" when nothing does.
func importOne(srcDir, dstRoot string, level int, name string) (string, error) {
	subject, err := os.ReadFile(filepath.Join(srcDir, "README.md"))
	if err != nil {
		return "", fmt.Errorf("reading README.md: %w", err)
	}
	meta, err := catalog.ParseSubject(string(subject))
	if err != nil {
		return "", err
	}

	outDir := filepath.Join(dstRoot, name)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(outDir, "subject.md"), subject, 0o644); err != nil {
		return "", err
	}

	if spanish, err := os.ReadFile(filepath.Join(srcDir, "spanish.md")); err == nil {
		if err := os.WriteFile(filepath.Join(outDir, "spanish.md"), spanish, 0o644); err != nil {
			return "", err
		}
	}

	// The reference solution is whichever .c file upstream ships. Any commented
	// out demo main it contains is left as is: it is inside a comment, so it
	// neither compiles nor interferes with linking against a driver.
	refName, err := singleFileWithSuffix(srcDir, ".c")
	if err != nil {
		return "", err
	}
	reference, err := os.ReadFile(filepath.Join(srcDir, refName))
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(outDir, "reference.c"), reference, 0o644); err != nil {
		return "", err
	}

	header, _ := singleFileWithSuffix(srcDir, ".h")
	if header != "" {
		b, err := os.ReadFile(filepath.Join(srcDir, header))
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(outDir, header), b, 0o644); err != nil {
			return "", err
		}
	}

	kind, kindCertain := guessKind(string(subject))
	expected := meta.ExpectedFile
	if expected == "" {
		expected = name + ".c" // a guess for the four glob subjects
	}

	out := catalog.Meta{
		Name:             name,
		Level:            level,
		Kind:             kind,
		ExpectedFile:     expected,
		AllowedFunctions: meta.AllowedFunctions,
		Prototype:        extractPrototype(string(subject)),
		Header:           header,
	}
	if out.AllowedFunctions == nil {
		out.AllowedFunctions = []string{}
	}
	encoded, err := yaml.Marshal(out)
	if err != nil {
		return "", err
	}
	banner := "# Generated by tools/import, then reviewed by hand.\n" +
		"# kind and expected_file are guesses until a human confirms them.\n"
	if err := os.WriteFile(filepath.Join(outDir, "meta.yaml"), append([]byte(banner), encoded...), 0o644); err != nil {
		return "", err
	}

	switch {
	case !kindCertain && meta.ExpectedFile == "":
		return "kind and expected_file both guessed", nil
	case !kindCertain:
		return "kind guessed as " + string(kind), nil
	case meta.ExpectedFile == "":
		return "expected_file guessed as " + expected, nil
	}
	return "", nil
}

// guessKind classifies a subject by the phrase it uses. The phrases cover 43
// of 56 subjects; the rest come back as a low-confidence guess for review.
func guessKind(subject string) (kind catalog.Kind, certain bool) {
	switch {
	case strings.Contains(subject, "function must be declared"):
		return catalog.KindFunction, true
	case strings.Contains(subject, "Write a program"):
		return catalog.KindProgram, true
	case strings.Contains(subject, "must be declared as follows"):
		return catalog.KindFunction, false
	default:
		return catalog.KindProgram, false
	}
}

// extractPrototype pulls the C declaration out of a subject, used to seed the
// candidate's workspace file. An empty result is fine for program exercises.
func extractPrototype(subject string) string {
	lines := strings.Split(subject, "\n")
	for i, line := range lines {
		// Subjects use both "declared as follows" and "prototyped as follows".
		if !strings.Contains(line, "declared as follows") &&
			!strings.Contains(line, "prototyped as follows") {
			continue
		}
		for _, candidate := range lines[i+1:] {
			candidate = strings.TrimSpace(candidate)
			if candidate == "" {
				continue
			}
			if strings.HasSuffix(candidate, ";") {
				return strings.Join(strings.Fields(candidate), " ")
			}
			return ""
		}
	}
	return ""
}

// singleFileWithSuffix returns the one file in dir with the given suffix, or
// "" if there is none. More than one is an error, because the importer would
// otherwise silently pick an arbitrary file as the reference solution.
func singleFileWithSuffix(dir, suffix string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	var found []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), suffix) {
			found = append(found, e.Name())
		}
	}
	switch len(found) {
	case 0:
		return "", nil
	case 1:
		return found[0], nil
	default:
		return "", fmt.Errorf("expected one %s file in %s, found %v", suffix, dir, found)
	}
}
